version: "3.9"

volumes:
  db-data:
  cache:

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15673:15672"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${MT_DB_USERNAME}
      POSTGRES_PASSWORD: ${MT_DB_PASSWORD}
      POSTGRES_DB: ${MT_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  msg-twilio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./media:/media/
      - ./static:/static/
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - .env