# Generated by Django 4.2.8 on 2024-02-05 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("start_timestamp", models.PositiveIntegerField()),
                ("end_timestamp", models.PositiveIntegerField()),
                ("user_email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=255)),
                ("cell_id", models.IntegerField()),
                ("reminded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
